### ISSUE TITLE
excalidraw support

### ISSUE THREAD

**Issue by 7flash** [MohrJonas/obsidian-ocr#1]

**Comment by 7flash** [comment]
https://github.com/excalidraw/excalidraw/issues/5379

**Comment by MohrJonas** [comment]
I don't really understand what your idea is 🤔
Could you maybe elaborate a little more?

**Comment by MohrJonas** [comment]
I'm not entirely sure if that's what he means.
He talks about AI-recommended images and stuff, so I'm not sure.
