### ISSUE TITLE
On Linux Clicking Search Results gives Error

### ISSUE THREAD

**Issue by evilgeniuschronicles** [MohrJonas/obsidian-ocr#11]
No matter what result I click, I always get the below error: "Unable to open file 1.2.1. Does it exist?"

![image](https://user-images.githubusercontent.com/1059864/196840265-c96c64fc-e4bf-4cd9-b054-4ef6eaed97da.png)

**Comment by MohrJonas** [comment]
Alright I found the problem and fixing it as we speak.
In case you're interested: In [processFile](https://github.com/MohrJonas/obsidian-ocr/blob/a7fb7a6ec7f9cdc41d80da19164f18fdd37e4e6a/src/utils/FileOps.ts#L27) the order of arguments is flipped whenOCRing an image (you can see the correct order when OCRing a pdf)
