### ISSUE TITLE
Potential for deleting too many .json files

### ISSUE THREAD

**Issue by evilgeniuschronicles** [MohrJonas/obsidian-ocr#17]
Looking at the code,  removeAllJsonFiles() has the possibility to delete too many files. It will recursively delete anything of the form     .filename.json excluding the .obsidian directory. However, other plugins might well be writing similar files and this will delete those. You might consider making the standard something less likely to collide, like .filename-ocr.json or .filename.ocr.json or other scheme.

Alternately, you could only consider .filename.json when filename exists, although that ups the developing and runtime complexity of the logic.

**Comment by evilgeniuschronicles** [comment]
For example:
![dont-delete-me](https://user-images.githubusercontent.com/1059864/197050299-18f7e7f6-b503-4813-b347-040ec74bda87.png)


![delete-all-transcripts](https://user-images.githubusercontent.com/1059864/197050320-f842474e-4989-4c58-a3e1-9d7e2a07c4cd.png)

![deleted](https://user-images.githubusercontent.com/1059864/197050351-4dbf56ea-760e-45d6-8c7f-718f62ce4192.png)

**Comment by MohrJonas** [comment]
You're right, the potential to delete other JSON files is pretty high when doing it like this.
The best way to address this would probably be, as you said, to change the name to something like `.filename.ocr.json`

**Comment by MohrJonas** [comment]
Fixed as of commit [1bd6841](https://github.com/MohrJonas/obsidian-ocr/commit/1bd6841c7c231922b6db6a24a716890e29246ad6)
Transcripts now have the suffix `.ocr.json` rather than just `.json`
