### ISSUE TITLE
Feature request: able to zoom in on search results

### ISSUE THREAD

**Issue by sidazhou** [MohrJonas/obsidian-ocr#22]
Thumbnails in search results are too small to see if the image is what I wanted.
Would be nice to be able to zoom in on the image using a keyboard shortcut or on-hover.

**Comment by MohrJonas** [comment]
Sounds like a good idea that should be fairly simple to implement with some CSS / HTML magic.
I'll give it a try

**Comment by MohrJonas** [comment]
Done as of commit [c02f4a3](https://github.com/MohrJonas/obsidian-ocr/commit/c02f4a337798698c4045f618edd43d901658e382)
