### ISSUE TITLE
"Dependencies aren't met"

### ISSUE THREAD

**Issue by NomarCub** [MohrJonas/obsidian-ocr#25]
I'm on Windows. I have Tesseract installed through chocolatey, it works in the terminal. I turned off PDF OCR, chose Tesseract as an OCR provider, chose eng as OCR language. Yet, when the plugin loads I get a `Dependencies aren't met` notification.

**Comment by MohrJonas** [comment]
`Dependencies aren't met` means that ImageMagick either isn't installed or that it wasn't found

**Comment by NomarCub** [comment]
Then it should say that instead.
I thought ImageMagick was only necessary for PDFs, which I disabled, so I thought the plugin would work fine. Does the plugin not work without it at all?

**Comment by MohrJonas** [comment]
ImageMagick is still a dependency, even when you're only transcribing images, though that might change in the future (As it says in the README, it's still in early development)

**Comment by NomarCub** [comment]
I see, thanks!
Please update the readme and the notifications to make this clearer.

**Comment by MohrJonas** [comment]
ImageMagick is now optional as of commit [2c9cc47](https://github.com/MohrJonas/obsidian-ocr/commit/2c9cc47545e927c2dd930d019ecc2a66589acca6)
