### ISSUE TITLE
Command to transcribe image(s)

### ISSUE THREAD

**Issue by NomarCub** [MohrJonas/obsidian-ocr#26]
It would be really useful for me to have a function to transcribe images into files. It could be something like have the plugin make an identically named markdown file. Or, more useful for me: having a command that writes a caption for all images in the current file.
The way the plugin is now, the integration with built in Obsidian features is poor, this would help that as well.

**Comment by MohrJonas** [comment]
For that feature, I'd recommend you to have a look at https://github.com/schlundd/obsidian-ocr-plugin

**Comment by NomarCub** [comment]
That plugin looks abandoned, isn't on Obsidian Community plugins, and only works online, not what I'm looking for.

**Comment by MohrJonas** [comment]
Though you seem to be right, that isn't really the objective of this plugin. If you're familiar with Obsidian plugin development (what you seem to be, judging from your repos), you could fork the project and adapt it to your needs.
