### ISSUE TITLE
Obsidian OCR unable to find Ghostscript

### ISSUE THREAD

**Issue by bwalkersc** [MohrJonas/obsidian-ocr#3]
### Issue: 
Obsidian OCR plugin is unable to find Ghostscript while finding all other dependencies just fine.
![image](https://user-images.githubusercontent.com/99450073/181843608-f0fc0833-4747-4350-9aa7-3fad7631db12.png)

### Attempted Solutions:
1. Registry edit, as detailed in [this comment](https://github.com/GenericMappingTools/gmt/issues/4231#issuecomment-868127347),
![image](https://user-images.githubusercontent.com/99450073/181842619-3cccb2af-11b7-4167-94de-345cb1de519a.png)
2. Installing an older version of GS 9.50 instead of GS 9.56.1
3. Setting proper environment variables:
![image](https://user-images.githubusercontent.com/99450073/181843029-a8019684-b02c-4ffc-a9e4-04c5ff74f994.png)

### System Information:
Operating System: Windows 11 Pro
Obsidian Version: v0.15.9
Tesseract Version: v5.2.0.20220712
GraphicsMagick Version: 1.3.35-Q16
Ghostscript Version: 9.56.1 and 9.50
Obsidian-OCR Version: 1.2.1

Any help is appreciated as this plugin will be huge for my productivity. Thank you.

**Comment by MohrJonas** [comment]
Could you please run `gs --version` in cmd and see if ghostscript is found?

**Comment by bwalkersc** [comment]
![image](https://user-images.githubusercontent.com/99450073/181845873-5b7dcf30-4392-4e62-8ed2-5ba16139e2aa.png)
Maybe I should try renaming the executable to gs.exe?

**Comment by MohrJonas** [comment]
Actually now that I see the name `gswin64` I actually remember that I renamed it to gs.exe 😁.
At least I think... 🤔
Definitely try it and see what happens 👍

**Comment by bwalkersc** [comment]
Fantastic! That stopped the dependency popup! Is there any way to force the plugin to index?
![image](https://user-images.githubusercontent.com/99450073/181846636-2dbe3b40-3d81-4878-b91b-ac852eba0663.png)
![image](https://user-images.githubusercontent.com/99450073/181846657-aeac6a1a-970b-4653-8407-1f32b917e001.png)

**Comment by MohrJonas** [comment]
There is a command called `Delete all transcripts` that you can invoke from the command palette (Ctrl+P)

**Comment by bwalkersc** [comment]
`Delete all transcripts` did not work, however manually deleting them in my obsidian vault did force a re-index.
![image](https://user-images.githubusercontent.com/99450073/181848257-cc1fe6a0-920d-4065-be5b-fa9f0a883944.png)
I will wait for it to reindex my vault and if the issue persists, I will open a seperate new issue.
