### ISSUE TITLE
Thoughts on implementing tesseract.js port?

### ISSUE THREAD

**Issue by GitMurf** [MohrJonas/obsidian-ocr#34]
Curious if you have looked at integrating https://github.com/naptha/tesseract.js#tesseractjs so that it gets installed automatically instead of requiring the user to install tesseract to their OS?

Here is npm: https://www.npmjs.com/package/tesseract.js

**Comment by MohrJonas** [comment]
I have never before heard of tesseract.js, definitely looks interesting.
At the moment, I don't really have the time to completely rewrite how OCR works.
If you have the time / are interested in contributing, feel free to implement it and create a pull request.

Leaving this issue open to track any further progress.

**Comment by GitMurf** [comment]
@MohrJonas makes sense and I totally know how it goes with time! Plugin development is everyone's "second job" ;) and always takes more time than we expect.

As far as tesseract.js, I had assumed it basically works the same as the installed tesseract as I believe there intent was to port it more or less to operate the same as the original tesseract. But I could be wrong.

But it makes sense why you didn't use it since you hadn't heard of it before ;) I had maybe thought there was a specific reason you weren't using it so that makes sense now. Nice work on the plugin!

**Comment by MohrJonas** [comment]
Alright, thank you for your patience 😅.
I've finally found the time to take a closer look at tesseractjs and am happy to announce initial (and still experimental) support for it as of commit 7e78de5.
No doubt there will still be bugs in the implementation, but it's still a step in the right direction 😀
