### ISSUE TITLE
Using imagemagick js port

### ISSUE THREAD

**Issue by khesed** [MohrJonas/obsidian-ocr#44]
Would you consider using an imagemagick version which is completely in js? This way, it is available automatically instead of requiring an install. This allows for mobile support.

e.g. [unix toolbox](https://github.com/manuels/unix-toolbox.js)'s version: https://github.com/manuels/unix-toolbox.js-imagemagick

**Comment by MohrJonas** [comment]
Interesting idea.
Definitely worth taking into consideration.

**Comment by MohrJonas** [comment]
Imagemagick js unfortunately does not contain the libraries required for PDF handling, apparently due to copyright, so unfortunately we can't use it.
