### ISSUE TITLE
Obsidan Freezes Up When Dependencies Not Met Popup Is Displayed

### ISSUE THREAD

**Issue by tekwizz123** [MohrJonas/obsidian-ocr#5]
Obsidian OCR installed via BRAT and keep getting this popup and then Obsidian freezes for a few seconds and I can't click on or really do anything during this time:

![image](https://user-images.githubusercontent.com/2746189/194801703-4669bc20-6263-464e-8707-b41c426f884c.png)

After a few seconds it goes away.

**Comment by MohrJonas** [comment]
The newest version doesn't have that popup anymore so it should be fixed.
